# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
